
name: CI/CT workflow for Go libraries packaged via go

on:
  push:
    branches:
      - master

jobs:
  set_stage:
    name: Determine Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set semantic_version
        id: branch_check
        run: |
          semantic_version=$(cat version)
          echo "semantic_version=$semantic_version" >> $GITHUB_OUTPUT
      - name: Print Semantic version
        run: echo "semantic_version for branch '${{ github.base_ref }}' is '${{ steps.branch_check.outputs.semantic_version }}'"
    outputs:
      semantic_version: ${{ steps.branch_check.outputs.semantic_version }}
  create-git-tags-from-version-file-job:
    runs-on: ubuntu-latest
    needs: [set_stage]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create git tag from version file
        uses: MGTheTrain/github-actions/.github/actions/create-git-tag-from-version-file@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  ci-ct-job-for-go-libraries:
    runs-on: ubuntu-latest
    needs: [create-git-tags-from-version-file-job]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Test Go repository
        uses: MGTheTrain/github-actions/.github/actions/test-go-repository@main
        with:
          SRC_WORKING_DIRECTORY: ./src
          TEST_WORKING_DIRECTORY: ./test
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORGANIZATION_ID: ${{ secrets.SNYK_ORGANIZATION_ID }}
      - name: Build and push zipped go repositories to a CloudSmtih repository
        uses: MGTheTrain/github-actions/.github/actions/build-and-push-zipped-go-repositories@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_OWNER: MGTheTrain
          GH_REPOSITORY: github-actions-for-go-packages
          CLOUDSMITH_REPOSITORY: ${{ secrets.CLOUDSMITH_REPOSITORY }}
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
          SRC_WORKING_DIRECTORY: ./src
          PACKAGE_VERSION: "0.1.0"